beeFit2019/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using beeFit2019.Data;
using beeFit2019.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace beeFit2019.Controllers
{
    public class ProfileController : Controller
    {
        private DataContext _conterxt;

        public ProfileController(DataContext dataContext)
        {
            _conterxt = dataContext;
        }

        [HttpGet]
        public async Task<IActionResult> SetProfileDetails()
        {
            var list = new List<SelectListItem>()
                {
                        new SelectListItem()
                {
                Text = "Body measurements",
                Value = "1"
                },
                new SelectListItem()
                {
                Text = "Race result",
                Value = "2"
                }
                };

            ViewBag.Options = list;


            return View();

        }

        [HttpPost]
        public async Task<IActionResult> SetProfileDetails(Body body)
        {
            if (ModelState.IsValid)
            {



                var user = _conterxt.Users.FirstOrDefault(x => x.Name == User.Identity.Name);


                Body paramsUpd = new Body
                {
                    Id = body.Id,
                    Day = body.Day,
                    LBic = body.LBic,
                    RBic = body.RBic,
                    Waist = body.Waist,
                    Chest = body.Chest,
                    LThigh = body.LThigh,
                    RThigh = body.RThigh,
                    UserId = user.Id

                };



                _conterxt.BodyParameters.Add(paramsUpd);

                await _conterxt.SaveChangesAsync();

                return View("SuccessfullyUpdatedProfile");
            }


            return View(body);
        }

        [HttpPut]
        public IActionResult UpdateProfileDetails(int id)
        {
            return View();
        }
    }
}

beeFit2019/Controllers/ProgressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using beeFit2019.Data;
using beeFit2019.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace beeFit2019.Controllers
{
    public class ProgressController : Controller
    {
        private DataContext _context;

        public ProgressController(DataContext dataContext)
        {
            _context = dataContext;
        }

        public async Task<IActionResult> ProgressTable()
        {
            var userId = await _context.Users.SingleOrDefaultAsync(x => x.Name == User.Identity.Name);

            var progressList = _context.BodyParameters.ToList();

            progressList = progressList.FindAll(x => x.UserId == userId.Id).ToList();
            
            if(progressList != null)
            {
            return View(progressList);
            }

            return View("NoProgressData");
            
        }
    }
}

beeFit2019/Controllers/TrainingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace beeFit2019.Controllers
{
    public class TrainingController : Controller
    {
        [HttpGet]
        public IActionResult ViewOfTheWeek()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EditTrainingPlan()
        {
            var list = new List<SelectListItem>()
            {
                    new SelectListItem()
                    {
                    Text = "1",
                    Value = "1"
                    },

                    new SelectListItem()
                    {
                    Text = "2",
                    Value = "2"
                    },
                    new SelectListItem()
                    {
                    Text = "3",
                    Value = "3"
                    },
                    new SelectListItem()
                    {
                    Text = "4",
                    Value = "4"
                    },

            };

            ViewBag.weeknumber = list;
            return View();
        }
    }
}

beeFit2019/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - beeFit2019</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-flatly.css" />
    </environment>
    <!--
        <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    -->

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container text-center font-italic font-weight-bold">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">BeeFit</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">


                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav mr-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link disabled text-white">Welcome  <span class="text-info"> @User.Identity.Name.ToUpper()  </span></a>
                            </li>



                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>


                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }

                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                        <div class="container">
                            <input class="form-control-sm mr-sm-2" type="text" placeholder="Search">
                            <button class="btn btn-sm btn-success my-2 my-sm-0" type="submit">Search</button>
                        </div>

                    </form>
                </div>
            </div>



        </nav>

        @if (User.Identity.IsAuthenticated)
        {
        <div class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <ul class="nav nav-pills">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Profile</a>
                        <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 38px, 0px);">
                            <a class="dropdown-item" asp-controller="Profile" asp-action="SetProfileDetails">Update profile</a>
                            <a class="dropdown-item" href="#">Your records</a>
                            <a class="dropdown-item" href="#">Set Goals</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Training plan</a>
                        <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 38px, 0px);">
                            <a class="dropdown-item" asp-controller="Training" asp-action="EditTrainingPlan">Edit training day</a>
                            <a class="dropdown-item" asp-controller="Training" asp-action="ViewOfTheWeek">Your training plan</a>
                            <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Progress" asp-action="ProgressTable">Progress table</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Gallery</a>
                    </li>

                </ul>
            </div>
            
        </div>


        }


    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - beeFit2019 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>